# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3103b68ad1e5ae5e8a9e147fa23e74c35b71565b6a4b328cc33a2f67d82d9cd6dfdeb1ba243088bd4b17919363deefea3a66abe7c92211a814d9efb15359c1d

test:
  secret_key_base: b04f0034f73c4730e3e7ece0a3be9152230112a9c188de8bad7d5f9f3b920b4efee392c48148846dae3a936488c86cbed7928023f0a0c5b2af7c3302f0aa2941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
